// THIS FILE IS AUTOGENERATED BY wb_intercon_gen
// ANY MANUAL CHANGES WILL BE LOST
`default_nettype none
module wb_intercon
   (input  wire        wb_clk_i,
    input  wire        wb_rst_i,
    input  wire [31:0] wb_cpu_adr_i,
    input  wire [31:0] wb_cpu_dat_i,
    input  wire  [3:0] wb_cpu_sel_i,
    input  wire        wb_cpu_we_i,
    input  wire        wb_cpu_cyc_i,
    input  wire        wb_cpu_stb_i,
    input  wire  [2:0] wb_cpu_cti_i,
    input  wire  [1:0] wb_cpu_bte_i,
    output wire [31:0] wb_cpu_rdt_o,
    output wire        wb_cpu_ack_o,
    output wire        wb_cpu_err_o,
    output wire        wb_cpu_rty_o,
    output wire [31:0] wb_rom_adr_o,
    output wire  [7:0] wb_rom_dat_o,
    output wire  [3:0] wb_rom_sel_o,
    output wire        wb_rom_we_o,
    output wire        wb_rom_cyc_o,
    output wire        wb_rom_stb_o,
    output wire  [2:0] wb_rom_cti_o,
    output wire  [1:0] wb_rom_bte_o,
    input  wire  [7:0] wb_rom_rdt_i,
    input  wire        wb_rom_ack_i,
    input  wire        wb_rom_err_i,
    input  wire        wb_rom_rty_i,
    output wire [31:0] wb_ext_flash_adr_o,
    output wire  [7:0] wb_ext_flash_dat_o,
    output wire  [3:0] wb_ext_flash_sel_o,
    output wire        wb_ext_flash_we_o,
    output wire        wb_ext_flash_cyc_o,
    output wire        wb_ext_flash_stb_o,
    output wire  [2:0] wb_ext_flash_cti_o,
    output wire  [1:0] wb_ext_flash_bte_o,
    input  wire  [7:0] wb_ext_flash_rdt_i,
    input  wire        wb_ext_flash_ack_i,
    input  wire        wb_ext_flash_err_i,
    input  wire        wb_ext_flash_rty_i,
    output wire [31:0] wb_spi_m_adr_o,
    output wire  [7:0] wb_spi_m_dat_o,
    output wire  [3:0] wb_spi_m_sel_o,
    output wire        wb_spi_m_we_o,
    output wire        wb_spi_m_cyc_o,
    output wire        wb_spi_m_stb_o,
    output wire  [2:0] wb_spi_m_cti_o,
    output wire  [1:0] wb_spi_m_bte_o,
    input  wire  [7:0] wb_spi_m_rdt_i,
    input  wire        wb_spi_m_ack_i,
    input  wire        wb_spi_m_err_i,
    input  wire        wb_spi_m_rty_i,
    output wire [31:0] wb_uart_adr_o,
    output wire  [7:0] wb_uart_dat_o,
    output wire  [3:0] wb_uart_sel_o,
    output wire        wb_uart_we_o,
    output wire        wb_uart_cyc_o,
    output wire        wb_uart_stb_o,
    output wire  [2:0] wb_uart_cti_o,
    output wire  [1:0] wb_uart_bte_o,
    input  wire  [7:0] wb_uart_rdt_i,
    input  wire        wb_uart_ack_i,
    input  wire        wb_uart_err_i,
    input  wire        wb_uart_rty_i,
    output wire [31:0] wb_ram_adr_o,
    output wire  [7:0] wb_ram_dat_o,
    output wire  [3:0] wb_ram_sel_o,
    output wire        wb_ram_we_o,
    output wire        wb_ram_cyc_o,
    output wire        wb_ram_stb_o,
    output wire  [2:0] wb_ram_cti_o,
    output wire  [1:0] wb_ram_bte_o,
    input  wire  [7:0] wb_ram_rdt_i,
    input  wire        wb_ram_ack_i,
    input  wire        wb_ram_err_i,
    input  wire        wb_ram_rty_i);

wire [31:0] wb_resize_rom_adr;
wire [31:0] wb_resize_rom_dat;
wire  [3:0] wb_resize_rom_sel;
wire        wb_resize_rom_we;
wire        wb_resize_rom_cyc;
wire        wb_resize_rom_stb;
wire  [2:0] wb_resize_rom_cti;
wire  [1:0] wb_resize_rom_bte;
wire [31:0] wb_resize_rom_rdt;
wire        wb_resize_rom_ack;
wire        wb_resize_rom_err;
wire        wb_resize_rom_rty;
wire [31:0] wb_resize_ext_flash_adr;
wire [31:0] wb_resize_ext_flash_dat;
wire  [3:0] wb_resize_ext_flash_sel;
wire        wb_resize_ext_flash_we;
wire        wb_resize_ext_flash_cyc;
wire        wb_resize_ext_flash_stb;
wire  [2:0] wb_resize_ext_flash_cti;
wire  [1:0] wb_resize_ext_flash_bte;
wire [31:0] wb_resize_ext_flash_rdt;
wire        wb_resize_ext_flash_ack;
wire        wb_resize_ext_flash_err;
wire        wb_resize_ext_flash_rty;
wire [31:0] wb_resize_spi_m_adr;
wire [31:0] wb_resize_spi_m_dat;
wire  [3:0] wb_resize_spi_m_sel;
wire        wb_resize_spi_m_we;
wire        wb_resize_spi_m_cyc;
wire        wb_resize_spi_m_stb;
wire  [2:0] wb_resize_spi_m_cti;
wire  [1:0] wb_resize_spi_m_bte;
wire [31:0] wb_resize_spi_m_rdt;
wire        wb_resize_spi_m_ack;
wire        wb_resize_spi_m_err;
wire        wb_resize_spi_m_rty;
wire [31:0] wb_resize_uart_adr;
wire [31:0] wb_resize_uart_dat;
wire  [3:0] wb_resize_uart_sel;
wire        wb_resize_uart_we;
wire        wb_resize_uart_cyc;
wire        wb_resize_uart_stb;
wire  [2:0] wb_resize_uart_cti;
wire  [1:0] wb_resize_uart_bte;
wire [31:0] wb_resize_uart_rdt;
wire        wb_resize_uart_ack;
wire        wb_resize_uart_err;
wire        wb_resize_uart_rty;
wire [31:0] wb_resize_ram_adr;
wire [31:0] wb_resize_ram_dat;
wire  [3:0] wb_resize_ram_sel;
wire        wb_resize_ram_we;
wire        wb_resize_ram_cyc;
wire        wb_resize_ram_stb;
wire  [2:0] wb_resize_ram_cti;
wire  [1:0] wb_resize_ram_bte;
wire [31:0] wb_resize_ram_rdt;
wire        wb_resize_ram_ack;
wire        wb_resize_ram_err;
wire        wb_resize_ram_rty;

// Drive downstream byte-select outputs (8-bit peripherals ignore most bits, but
// the interconnect still exposes 4-bit SEL to remain Wishbone-compatible).
assign wb_rom_sel_o       = wb_resize_rom_sel;
assign wb_ext_flash_sel_o = wb_resize_ext_flash_sel;
assign wb_spi_m_sel_o     = wb_resize_spi_m_sel;
assign wb_uart_sel_o      = wb_resize_uart_sel;
assign wb_ram_sel_o       = wb_resize_ram_sel;

wb_mux
  #(.num_devices (5),
    .MATCH_ADDR  ({32'h00004000, 32'h00008000, 32'h00002000, 32'h00000000, 32'h00000020}),
    .MATCH_MASK  ({32'hfffffff0, 32'hfffff000, 32'hffffd001, 32'hffffffe0, 32'hffffffe0}))
 wb_mux_cpu
   (.wb_clk_i  (wb_clk_i),
    .wb_rst_i  (wb_rst_i),
    .wbm_adr_i (wb_cpu_adr_i),
    .wbm_dat_i (wb_cpu_dat_i),
    .wbm_sel_i (wb_cpu_sel_i),
    .wbm_we_i  (wb_cpu_we_i),
    .wbm_cyc_i (wb_cpu_cyc_i),
    .wbm_stb_i (wb_cpu_stb_i),
    .wbm_cti_i (wb_cpu_cti_i),
    .wbm_bte_i (wb_cpu_bte_i),
    .wbm_dat_o (wb_cpu_rdt_o),
    .wbm_ack_o (wb_cpu_ack_o),
    .wbm_err_o (wb_cpu_err_o),
    .wbm_rty_o (wb_cpu_rty_o),
    .wbs_adr_o ({wb_resize_rom_adr, wb_resize_ram_adr, wb_resize_ext_flash_adr, wb_resize_spi_m_adr, wb_resize_uart_adr}),
    .wbs_dat_o ({wb_resize_rom_dat, wb_resize_ram_dat, wb_resize_ext_flash_dat, wb_resize_spi_m_dat, wb_resize_uart_dat}),
    .wbs_sel_o ({wb_resize_rom_sel, wb_resize_ram_sel, wb_resize_ext_flash_sel, wb_resize_spi_m_sel, wb_resize_uart_sel}),
    .wbs_we_o  ({wb_resize_rom_we, wb_resize_ram_we, wb_resize_ext_flash_we, wb_resize_spi_m_we, wb_resize_uart_we}),
    .wbs_cyc_o ({wb_resize_rom_cyc, wb_resize_ram_cyc, wb_resize_ext_flash_cyc, wb_resize_spi_m_cyc, wb_resize_uart_cyc}),
    .wbs_stb_o ({wb_resize_rom_stb, wb_resize_ram_stb, wb_resize_ext_flash_stb, wb_resize_spi_m_stb, wb_resize_uart_stb}),
    .wbs_cti_o ({wb_resize_rom_cti, wb_resize_ram_cti, wb_resize_ext_flash_cti, wb_resize_spi_m_cti, wb_resize_uart_cti}),
    .wbs_bte_o ({wb_resize_rom_bte, wb_resize_ram_bte, wb_resize_ext_flash_bte, wb_resize_spi_m_bte, wb_resize_uart_bte}),
    .wbs_dat_i ({wb_resize_rom_rdt, wb_resize_ram_rdt, wb_resize_ext_flash_rdt, wb_resize_spi_m_rdt, wb_resize_uart_rdt}),
    .wbs_ack_i ({wb_resize_rom_ack, wb_resize_ram_ack, wb_resize_ext_flash_ack, wb_resize_spi_m_ack, wb_resize_uart_ack}),
    .wbs_err_i ({wb_resize_rom_err, wb_resize_ram_err, wb_resize_ext_flash_err, wb_resize_spi_m_err, wb_resize_uart_err}),
    .wbs_rty_i ({wb_resize_rom_rty, wb_resize_ram_rty, wb_resize_ext_flash_rty, wb_resize_spi_m_rty, wb_resize_uart_rty}));

wb_data_resize
  #(.aw     (32),
    .mdw    (32),
    .sdw    (8),
    .endian ("little"))
 wb_data_resize_rom
   (.wbm_adr_i (wb_resize_rom_adr),
    .wbm_dat_i (wb_resize_rom_dat),
    .wbm_sel_i (wb_resize_rom_sel),
    .wbm_we_i  (wb_resize_rom_we),
    .wbm_cyc_i (wb_resize_rom_cyc),
    .wbm_stb_i (wb_resize_rom_stb),
    .wbm_cti_i (wb_resize_rom_cti),
    .wbm_bte_i (wb_resize_rom_bte),
    .wbm_dat_o (wb_resize_rom_rdt),
    .wbm_ack_o (wb_resize_rom_ack),
    .wbm_err_o (wb_resize_rom_err),
    .wbm_rty_o (wb_resize_rom_rty),
    .wbs_adr_o (wb_rom_adr_o),
    .wbs_dat_o (wb_rom_dat_o),
    .wbs_we_o  (wb_rom_we_o),
    .wbs_cyc_o (wb_rom_cyc_o),
    .wbs_stb_o (wb_rom_stb_o),
    .wbs_cti_o (wb_rom_cti_o),
    .wbs_bte_o (wb_rom_bte_o),
    .wbs_dat_i (wb_rom_rdt_i),
    .wbs_ack_i (wb_rom_ack_i),
    .wbs_err_i (wb_rom_err_i),
    .wbs_rty_i (wb_rom_rty_i));

wb_data_resize
  #(.aw     (32),
    .mdw    (32),
    .sdw    (8),
    .endian ("little"))
 wb_data_resize_ext_flash
   (.wbm_adr_i (wb_resize_ext_flash_adr),
    .wbm_dat_i (wb_resize_ext_flash_dat),
    .wbm_sel_i (wb_resize_ext_flash_sel),
    .wbm_we_i  (wb_resize_ext_flash_we),
    .wbm_cyc_i (wb_resize_ext_flash_cyc),
    .wbm_stb_i (wb_resize_ext_flash_stb),
    .wbm_cti_i (wb_resize_ext_flash_cti),
    .wbm_bte_i (wb_resize_ext_flash_bte),
    .wbm_dat_o (wb_resize_ext_flash_rdt),
    .wbm_ack_o (wb_resize_ext_flash_ack),
    .wbm_err_o (wb_resize_ext_flash_err),
    .wbm_rty_o (wb_resize_ext_flash_rty),
    .wbs_adr_o (wb_ext_flash_adr_o),
    .wbs_dat_o (wb_ext_flash_dat_o),
    .wbs_we_o  (wb_ext_flash_we_o),
    .wbs_cyc_o (wb_ext_flash_cyc_o),
    .wbs_stb_o (wb_ext_flash_stb_o),
    .wbs_cti_o (wb_ext_flash_cti_o),
    .wbs_bte_o (wb_ext_flash_bte_o),
    .wbs_dat_i (wb_ext_flash_rdt_i),
    .wbs_ack_i (wb_ext_flash_ack_i),
    .wbs_err_i (wb_ext_flash_err_i),
    .wbs_rty_i (wb_ext_flash_rty_i));

wb_data_resize
  #(.aw     (32),
    .mdw    (32),
    .sdw    (8),
    .endian ("little"))
 wb_data_resize_spi_m
   (.wbm_adr_i (wb_resize_spi_m_adr),
    .wbm_dat_i (wb_resize_spi_m_dat),
    .wbm_sel_i (wb_resize_spi_m_sel),
    .wbm_we_i  (wb_resize_spi_m_we),
    .wbm_cyc_i (wb_resize_spi_m_cyc),
    .wbm_stb_i (wb_resize_spi_m_stb),
    .wbm_cti_i (wb_resize_spi_m_cti),
    .wbm_bte_i (wb_resize_spi_m_bte),
    .wbm_dat_o (wb_resize_spi_m_rdt),
    .wbm_ack_o (wb_resize_spi_m_ack),
    .wbm_err_o (wb_resize_spi_m_err),
    .wbm_rty_o (wb_resize_spi_m_rty),
    .wbs_adr_o (wb_spi_m_adr_o),
    .wbs_dat_o (wb_spi_m_dat_o),
    .wbs_we_o  (wb_spi_m_we_o),
    .wbs_cyc_o (wb_spi_m_cyc_o),
    .wbs_stb_o (wb_spi_m_stb_o),
    .wbs_cti_o (wb_spi_m_cti_o),
    .wbs_bte_o (wb_spi_m_bte_o),
    .wbs_dat_i (wb_spi_m_rdt_i),
    .wbs_ack_i (wb_spi_m_ack_i),
    .wbs_err_i (wb_spi_m_err_i),
    .wbs_rty_i (wb_spi_m_rty_i));

wb_data_resize
  #(.aw     (32),
    .mdw    (32),
    .sdw    (8),
    .endian ("little"))
 wb_data_resize_uart
   (.wbm_adr_i (wb_resize_uart_adr),
    .wbm_dat_i (wb_resize_uart_dat),
    .wbm_sel_i (wb_resize_uart_sel),
    .wbm_we_i  (wb_resize_uart_we),
    .wbm_cyc_i (wb_resize_uart_cyc),
    .wbm_stb_i (wb_resize_uart_stb),
    .wbm_cti_i (wb_resize_uart_cti),
    .wbm_bte_i (wb_resize_uart_bte),
    .wbm_dat_o (wb_resize_uart_rdt),
    .wbm_ack_o (wb_resize_uart_ack),
    .wbm_err_o (wb_resize_uart_err),
    .wbm_rty_o (wb_resize_uart_rty),
    .wbs_adr_o (wb_uart_adr_o),
    .wbs_dat_o (wb_uart_dat_o),
    .wbs_we_o  (wb_uart_we_o),
    .wbs_cyc_o (wb_uart_cyc_o),
    .wbs_stb_o (wb_uart_stb_o),
    .wbs_cti_o (wb_uart_cti_o),
    .wbs_bte_o (wb_uart_bte_o),
    .wbs_dat_i (wb_uart_rdt_i),
    .wbs_ack_i (wb_uart_ack_i),
    .wbs_err_i (wb_uart_err_i),
    .wbs_rty_i (wb_uart_rty_i));

wb_data_resize
  #(.aw     (32),
    .mdw    (32),
    .sdw    (8),
    .endian ("little"))
 wb_data_resize_ram
   (.wbm_adr_i (wb_resize_ram_adr),
    .wbm_dat_i (wb_resize_ram_dat),
    .wbm_sel_i (wb_resize_ram_sel),
    .wbm_we_i  (wb_resize_ram_we),
    .wbm_cyc_i (wb_resize_ram_cyc),
    .wbm_stb_i (wb_resize_ram_stb),
    .wbm_cti_i (wb_resize_ram_cti),
    .wbm_bte_i (wb_resize_ram_bte),
    .wbm_dat_o (wb_resize_ram_rdt),
    .wbm_ack_o (wb_resize_ram_ack),
    .wbm_err_o (wb_resize_ram_err),
    .wbm_rty_o (wb_resize_ram_rty),
    .wbs_adr_o (wb_ram_adr_o),
    .wbs_dat_o (wb_ram_dat_o),
    .wbs_we_o  (wb_ram_we_o),
    .wbs_cyc_o (wb_ram_cyc_o),
    .wbs_stb_o (wb_ram_stb_o),
    .wbs_cti_o (wb_ram_cti_o),
    .wbs_bte_o (wb_ram_bte_o),
    .wbs_dat_i (wb_ram_rdt_i),
    .wbs_ack_i (wb_ram_ack_i),
    .wbs_err_i (wb_ram_err_i),
    .wbs_rty_i (wb_ram_rty_i));

endmodule
