// Auto-generated by tools/yaml_to_verilog_regbank.py
module wb_spi_mem_ctrl_regs (
  input  wire        clk,
  input  wire        rst_n,
  // Wishbone interface
  input  wire [7:0]  wb_addr_i,
  input  wire [31:0] wb_wdata_i,
  input  wire        wb_we_i,
  input  wire        wb_stb_i,
  output reg  [31:0] wb_rdata_o,
  output wire        wb_ack_o,
  output wire        irq_o,
  // register bank interface
  output wire [7:0]  spi_ctrl_o,
  input  wire [7:0]  byte_count_rdata_i,
  output reg  [7:0]  byte_count_wdata_o,
  output reg         byte_count_we_o,
  input  wire [7:0]  bytes_fetched_i,
  output wire [7:0]  irq_status_o,
  output wire [7:0]  irq_enable_o,
  output reg         spi_ctrl_start_pulse_o,
  output reg         spi_ctrl_stop_pulse_o,
  input  wire        irq_status_trans_done_set_i
);

  // Control commands for transfer start/stop.
  localparam [7:0] ADDR_SPI_CTRL = 8'h0;
  wire sel_spi_ctrl = (wb_addr_i == ADDR_SPI_CTRL);
  reg [7:0] spi_ctrl_reg;
  assign spi_ctrl_o = spi_ctrl_reg;

  // Number of bytes to fetch in the sequential read.
  localparam [7:0] ADDR_BYTE_COUNT = 8'h4;
  wire sel_byte_count = (wb_addr_i == ADDR_BYTE_COUNT);

  // Counter of bytes fetched so far.
  localparam [7:0] ADDR_BYTES_FETCHED = 8'h8;
  wire sel_bytes_fetched = (wb_addr_i == ADDR_BYTES_FETCHED);

  // Interrupt status flags.
  localparam [7:0] ADDR_IRQ_STATUS = 8'hC;
  wire sel_irq_status = (wb_addr_i == ADDR_IRQ_STATUS);
  reg [7:0] irq_status_reg;
  assign irq_status_o = irq_status_reg;

  // Interrupt enable controls.
  localparam [7:0] ADDR_IRQ_ENABLE = 8'h10;
  wire sel_irq_enable = (wb_addr_i == ADDR_IRQ_ENABLE);
  reg [7:0] irq_enable_reg;
  assign irq_enable_o = irq_enable_reg;

  assign wb_ack_o = wb_stb_i;

  always @* begin
    wb_rdata_o = 32'd0;
    case (wb_addr_i)
      ADDR_SPI_CTRL: wb_rdata_o = {{24{1'b0}}, spi_ctrl_reg};
      ADDR_BYTE_COUNT: wb_rdata_o = {{24{1'b0}}, byte_count_rdata_i};
      ADDR_BYTES_FETCHED: wb_rdata_o = {{24{1'b0}}, bytes_fetched_i};
      ADDR_IRQ_STATUS: wb_rdata_o = {{24{1'b0}}, irq_status_reg};
      ADDR_IRQ_ENABLE: wb_rdata_o = {{24{1'b0}}, irq_enable_reg};
      default: wb_rdata_o = '0;
    endcase
  end

  always @(posedge clk) begin
    if (!rst_n) begin
      spi_ctrl_reg <= 8'h0;
      spi_ctrl_start_pulse_o <= 1'b0;
      spi_ctrl_stop_pulse_o <= 1'b0;
      byte_count_wdata_o <= 8'd0;
      byte_count_we_o <= 1'b0;
      irq_status_reg <= 8'h0;
      irq_enable_reg <= 8'h0;
    end else begin
      spi_ctrl_start_pulse_o <= 1'b0;
      spi_ctrl_stop_pulse_o <= 1'b0;
      byte_count_we_o <= 1'b0;
      if (wb_stb_i && wb_we_i) begin
        if (sel_spi_ctrl) begin
          spi_ctrl_start_pulse_o <= wb_wdata_i[0];
          spi_ctrl_stop_pulse_o <= wb_wdata_i[1];
        end
        if (sel_byte_count) begin
          byte_count_wdata_o <= wb_wdata_i[7:0];
          byte_count_we_o <= 1'b1;
        end
        if (sel_bytes_fetched) begin
        end
        if (sel_irq_status) begin
          irq_status_reg[0] <= irq_status_reg[0] & ~wb_wdata_i[0];
        end
        if (sel_irq_enable) begin
          irq_enable_reg[0] <= wb_wdata_i[0];
        end
      end
      if (irq_status_trans_done_set_i) irq_status_reg[0] <= {1{1'b1}};
    end
  end

  // Asserted when transfer-complete interrupt is active.
  assign irq_o = (irq_status_reg[0] && irq_enable_reg[0]);
endmodule
