// Auto-generated by Coral reg-gen

module wb_spi_mem_ctrl_regs (
  input  wire       clk,
  input  wire       rst_n,

  // Wishbone interface
  input  wire [4:0] wb_addr_i,
  input  wire [7:0] wb_wdata_i,
  input  wire       wb_we_i,
  input  wire       wb_stb_i,
  output reg  [7:0] wb_rdata_o,
  output wire       wb_ack_o,
  output wire       irq_o,

  // Register bank interface
  input  wire       ext_f_SPI_STATUS_spi_busy_i,
  input  wire       ext_f_SPI_STATUS_spi_error_i,
  input  wire [7:0] r_BYTES_FETCHED_i,
  input  wire       ext_f_IRQ_STATUS_byte_done_i,
  input  wire       ext_f_IRQ_STATUS_block_done_i,

  output wire       f_SPI_CTRL_fetch_mode_o,
  output wire [7:0] r_MAX_FETCH_SIZE_o,
  output wire       f_IRQ_ENABLE_byte_done_en_o,
  output wire       f_IRQ_ENABLE_block_done_en_o,
  output reg        f_SPI_CTRL_start_pulse_o,
  output reg        ext_f_IRQ_STATUS_byte_done_clr_o,
  output reg        ext_f_IRQ_STATUS_block_done_clr_o
);

  //------------------------------------------------------------
  // Address Map Paramaters 
  //------------------------------------------------------------

  localparam [4:0] ADDR_SPI_CTRL       = 5'h0;
  localparam [4:0] ADDR_SPI_STATUS     = 5'h4;
  localparam [4:0] ADDR_MAX_FETCH_SIZE = 5'h8;
  localparam [4:0] ADDR_BYTES_FETCHED  = 5'hC;
  localparam [4:0] ADDR_IRQ_STATUS     = 5'h10;
  localparam [4:0] ADDR_IRQ_ENABLE     = 5'h14;

  //------------------------------------------------------------
  // Internal Signals 
  //------------------------------------------------------------

  // Register: SPI_CTRL
  // Access: RW
  // Control commands for transfer start/stop.
  reg        spi_ctrl_start_reg;
  reg        spi_ctrl_fetch_mode_reg;
  wire       sel_spi_ctrl;

  // Register: SPI_STATUS
  // Access: RO
  // Status register for the SPI memory controller.
  wire       sel_spi_status;

  // Register: MAX_FETCH_SIZE
  // Access: RW
  // Counter of bytes fetched so far.
  reg  [7:0] max_fetch_size_reg;
  wire       sel_max_fetch_size;

  // Register: BYTES_FETCHED
  // Access: RO
  // Counter of bytes fetched so far.
  wire       sel_bytes_fetched;

  // Register: IRQ_STATUS
  // Access: RW
  // Interrupt status flags.
  wire       sel_irq_status;

  // Register: IRQ_ENABLE
  // Access: RW
  // Interrupt enable controls.
  reg        irq_enable_byte_done_en_reg;
  reg        irq_enable_block_done_en_reg;
  wire       sel_irq_enable;

  //------------------------------------------------------------
  // Address Decode Logic 
  //------------------------------------------------------------

  assign sel_spi_ctrl                 = (wb_addr_i == ADDR_SPI_CTRL);
  assign f_SPI_CTRL_fetch_mode_o      = spi_ctrl_fetch_mode_reg;
  assign sel_spi_status               = (wb_addr_i == ADDR_SPI_STATUS);
  assign sel_max_fetch_size           = (wb_addr_i == ADDR_MAX_FETCH_SIZE);
  assign r_MAX_FETCH_SIZE_o           = max_fetch_size_reg;
  assign sel_bytes_fetched            = (wb_addr_i == ADDR_BYTES_FETCHED);
  assign sel_irq_status               = (wb_addr_i == ADDR_IRQ_STATUS);
  assign sel_irq_enable               = (wb_addr_i == ADDR_IRQ_ENABLE);
  assign f_IRQ_ENABLE_byte_done_en_o  = irq_enable_byte_done_en_reg;
  assign f_IRQ_ENABLE_block_done_en_o = irq_enable_block_done_en_reg;
  assign wb_ack_o = wb_stb_i;

  //------------------------------------------------------------
  // Read Logic 
  //------------------------------------------------------------

  always @* begin
    wb_rdata_o = 8'd0;
    case (wb_addr_i)
      ADDR_SPI_CTRL      : wb_rdata_o = {6'd0, spi_ctrl_fetch_mode_reg, spi_ctrl_start_reg};
      ADDR_SPI_STATUS    : wb_rdata_o = {6'd0, ext_f_SPI_STATUS_spi_error_i, ext_f_SPI_STATUS_spi_busy_i};
      ADDR_MAX_FETCH_SIZE: wb_rdata_o = max_fetch_size_reg;
      ADDR_BYTES_FETCHED : wb_rdata_o = r_BYTES_FETCHED_i;
      ADDR_IRQ_STATUS    : wb_rdata_o = {6'd0, ext_f_IRQ_STATUS_block_done_i, ext_f_IRQ_STATUS_byte_done_i};
      ADDR_IRQ_ENABLE    : wb_rdata_o = {{6{1'b0}}, {irq_enable_block_done_en_reg, irq_enable_byte_done_en_reg}};
      default: wb_rdata_o = '0;
    endcase
  end

  //------------------------------------------------------------
  // Write Logic 
  //------------------------------------------------------------

  always @(posedge clk) begin
    if (!rst_n) begin
      spi_ctrl_start_reg <= 1'h0;
      spi_ctrl_fetch_mode_reg <= 1'h1;
      f_SPI_CTRL_start_pulse_o <= 1'b0;
      max_fetch_size_reg <= 8'hFF;
      ext_f_IRQ_STATUS_byte_done_clr_o <= 1'b0;
      ext_f_IRQ_STATUS_block_done_clr_o <= 1'b0;
      irq_enable_byte_done_en_reg <= 1'h0;
      irq_enable_block_done_en_reg <= 1'h0;
    end else begin
      f_SPI_CTRL_start_pulse_o <= 1'b0;
      ext_f_IRQ_STATUS_byte_done_clr_o <= 1'b0;
      ext_f_IRQ_STATUS_block_done_clr_o <= 1'b0;
      if (wb_stb_i && wb_we_i) begin
        if (sel_spi_ctrl) begin
          f_SPI_CTRL_start_pulse_o <= wb_wdata_i[0];
          spi_ctrl_fetch_mode_reg <= wb_wdata_i[1];
        end
        if (sel_max_fetch_size) begin
          max_fetch_size_reg <= wb_wdata_i[7:0];
        end
        if (sel_irq_status) begin
          ext_f_IRQ_STATUS_byte_done_clr_o <= wb_wdata_i[0];
          ext_f_IRQ_STATUS_block_done_clr_o <= wb_wdata_i[1];
        end
        if (sel_irq_enable) begin
          irq_enable_byte_done_en_reg <= wb_wdata_i[0];
          irq_enable_block_done_en_reg <= wb_wdata_i[1];
        end
      end
    end
  end

  //------------------------------------------------------------
  // IRQ Logic 
  //------------------------------------------------------------

  // Asserted when an interrupt is active
  assign irq_o = (ext_f_IRQ_STATUS_byte_done_i && irq_enable_byte_done_en_reg || ext_f_IRQ_STATUS_block_done_i && irq_enable_block_done_en_reg);

endmodule
